name = "tekken_query"
version = "0.1.5"
defaultTargets = ["tekken_query", "frame_check"]

[[lean_lib]]
name = "TekkenQuery"

[[lean_exe]]
name = "tekken_query"
root = "Main"

[[lean_exe]]
name = "frame_check"
root = "FrameCheck"
