#!/usr/bin/env python3
"""Write the third-party license notices for Tekken Query's release binaries.

The binaries contain more than Tekken Query's own MIT-licensed code:

- tekken_query statically links the Lean 4 runtime and standard library
  (Apache-2.0) together with the libraries the Lean toolchain bundles: GMP
  (LGPL-3.0), LLVM libc++/libc++abi/libunwind and libuv.
- tekken-cli and the tekken-query launcher link the Rust standard library and
  the Rust crates of their dependency graph.

Lean's own LICENSE and LICENSES files come from the Lean toolchain that built
the binary; libuv, GPL-3.0 and Rust standard-library texts are tracked in
`licenses/`; each crate's license files come from its source in the Cargo
registry. The release workflow runs this on every platform after building.

Usage: python3 scripts/third_party_licenses.py [--output PATH] [--lean-prefix DIR]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFESTS = ("cli/Cargo.toml", "launcher/Cargo.toml")
LICENSE_FILE_PREFIXES = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "COPYRIGHT", "UNLICENSE")
REPOSITORY = "https://github.com/rekoriku/Tekken-Query"
RULE = "=" * 78


def run(command: list[str]) -> str:
    """Run a command in the project root and return its standard output."""
    return subprocess.run(command, cwd=ROOT, check=True, capture_output=True, text=True).stdout


def host_triple() -> str:
    """The Rust host target, so platform-specific dependencies are resolved for it."""
    for line in run(["rustc", "-vV"]).splitlines():
        if line.startswith("host: "):
            return line.removeprefix("host: ")
    raise SystemExit("rustc -vV did not report a host triple")


def linked_crates(triple: str) -> list[dict]:
    """Crates linked into the Rust binaries: normal dependencies, without
    build-only dependencies, proc macros or the project's own packages."""
    crates: dict[str, dict] = {}
    for manifest in MANIFESTS:
        metadata = json.loads(run([
            "cargo", "metadata", "--format-version", "1", "--locked",
            "--manifest-path", manifest, "--filter-platform", triple,
        ]))
        packages = {p["id"]: p for p in metadata["packages"]}
        nodes = {n["id"]: n for n in metadata["resolve"]["nodes"]}
        root = metadata["resolve"]["root"]
        pending, seen = [root], {root}
        while pending:
            for dep in nodes[pending.pop()]["deps"]:
                normal = any(kind["kind"] is None for kind in dep["dep_kinds"])
                package = packages[dep["pkg"]]
                proc_macro = any("proc-macro" in t["kind"] for t in package["targets"])
                if normal and not proc_macro and dep["pkg"] not in seen:
                    seen.add(dep["pkg"])
                    pending.append(dep["pkg"])
        for package_id in seen - {root}:
            package = packages[package_id]
            crates[f'{package["name"]} {package["version"]}'] = package
    return [crates[key] for key in sorted(crates)]


def license_texts(package: dict) -> list[tuple[str, str]]:
    """The license files a crate ships, as (file name, text) pairs."""
    directory = Path(package["manifest_path"]).parent
    names = set()
    if package.get("license_file"):
        names.add(package["license_file"])
    names.update(
        p.name for p in directory.iterdir()
        if p.is_file() and p.name.upper().startswith(LICENSE_FILE_PREFIXES)
    )
    return [(name, (directory / name).read_text(encoding="utf-8").strip()) for name in sorted(names)]


def section(title: str, body: str) -> str:
    return f"{RULE}\n{title}\n{RULE}\n\n{body.strip()}\n\n"


def tracked(name: str) -> str:
    return (ROOT / "licenses" / name).read_text(encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", type=Path, help="write here instead of standard output")
    parser.add_argument("--lean-prefix", type=Path, help="Lean toolchain directory (default: lean --print-prefix)")
    args = parser.parse_args()

    lean_prefix = args.lean_prefix or Path(run(["lean", "--print-prefix"]).strip())
    lean_version = run(["lean", "--version"]).strip() if args.lean_prefix is None else str(lean_prefix)
    triple = host_triple()
    crates = linked_crates(triple)

    out = [
        "Tekken Query third-party notices\n"
        f"{RULE}\n\n"
        "Tekken Query itself is MIT licensed (see LICENSE). Its release binaries also\n"
        "contain the third-party software below, distributed under these licenses.\n"
        f"Generated by scripts/third_party_licenses.py for {triple}.\n\n"
        "Contents:\n"
        "  1. Lean 4 runtime and standard library (tekken_query) - Apache-2.0\n"
        "  2. Libraries bundled by the Lean toolchain (tekken_query) - GMP, LLVM, ...\n"
        "  3. libuv 1.48.0 (tekken_query) - MIT\n"
        "  4. GNU General Public License v3 (referenced by GMP's LGPL-3.0)\n"
        "  5. Rust standard library (tekken-cli, tekken-query) - MIT OR Apache-2.0\n"
        f"  6. Rust crates (tekken-cli, tekken-query) - {len(crates)} crates\n\n",
        section(
            f"1. Lean 4 runtime and standard library ({lean_version})",
            "Source: https://github.com/leanprover/lean4\n\n"
            + (lean_prefix / "LICENSE").read_text(encoding="utf-8"),
        ),
        section(
            "2. Libraries bundled by the Lean toolchain",
            "tekken_query statically links GMP (the GNU Multiple Precision Arithmetic\n"
            "Library, LGPL-3.0) and LLVM libc++, libc++abi and libunwind as shipped by the\n"
            "Lean toolchain. GMP source: https://gmplib.org/. Under LGPL-3.0 you may\n"
            "relink tekken_query with a modified GMP: the complete source of Tekken Query\n"
            f"is available at {REPOSITORY}. The Lean toolchain's notices for the libraries\n"
            "it bundles follow verbatim.\n\n"
            + (lean_prefix / "LICENSES").read_text(encoding="utf-8"),
        ),
        section(
            "3. libuv 1.48.0",
            "Source: https://github.com/libuv/libuv\n\n"
            + tracked("libuv-1.48.0.txt") + "\n" + tracked("libuv-1.48.0-extra.txt"),
        ),
        section("4. GNU General Public License v3", tracked("GPL-3.0.txt")),
        section(
            "5. Rust standard library",
            "Source: https://github.com/rust-lang/rust\n\n"
            + tracked("rust-COPYRIGHT.txt") + "\n" + tracked("rust-LICENSE-MIT.txt"),
        ),
    ]
    crate_parts = []
    for package in crates:
        header = f'{package["name"]} {package["version"]} - {package.get("license") or "see files"}'
        source = package.get("repository") or package.get("homepage") or "crates.io"
        texts = license_texts(package)
        if not texts:
            raise SystemExit(f'{package["name"]} {package["version"]} ships no license file')
        body = "\n\n".join(f"--- {name} ---\n{text}" for name, text in texts)
        release = f'https://crates.io/crates/{package["name"]}/{package["version"]}'
        crate_parts.append(f"{'-' * 78}\n{header}\nSource: {source}\nThis version: {release}\n\n{body}\n")
    out.append(section(
        "6. Rust crates",
        "Each crate's source is available at the exact version listed (the 'This\n"
        "version' link), as MPL-2.0 requires for colored.\n\n" + "\n".join(crate_parts),
    ))

    text = "".join(out)
    if args.output is None:
        sys.stdout.write(text)
    else:
        args.output.write_text(text, encoding="utf-8")
        print(f"wrote {args.output} ({len(crates)} crates)", file=sys.stderr)


if __name__ == "__main__":
    main()
